use_frameworks!

target 'SmartMockLib_Example' do
  pod 'SmartMockLib', :path => '../../'
  pod 'Alamofire', '~> 4.0'
  pod 'AlamofireObjectMapper', '~> 4.0'
  pod 'AlamofireImage', '~> 3.0'

  target 'SmartMockLib_Tests' do
    inherit! :search_paths
    pod 'SmartMockLib', :path => '../../'
  end
end
